
(function(){
'use strict';
const STORE='albert_grammar_v24_complete';
const UI={active:{},answers:{},submitted:{}};
try{Object.assign(UI,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch(e){}
function save(){try{localStorage.setItem(STORE,JSON.stringify(UI))}catch(e){}}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exKey(uid,eid){return uid+'::'+eid}
function ansKey(uid,eid,qi,si){return uid+'::'+eid+'::'+qi+'::'+si}
function currentUnit(){return (typeof state!=='undefined'&&state&&state.unit)||''}
function unitData(){return V24_COMPLETE_DATA[currentUnit()]||null}
function flattenSlots(ex){const out=[];(ex.questions||[]).forEach((q,qi)=>(q.slots||[]).forEach((s,si)=>out.push({q,qi,s,si,key:ansKey(currentUnit(),ex.id,qi,si)})));return out}
function answered(ex){return flattenSlots(ex).filter(x=>String(UI.answers[x.key]??'').trim()).length}
function allAnswered(ex){const a=flattenSlots(ex);return a.length>0&&a.every(x=>String(UI.answers[x.key]??'').trim())}
function contractions(s){let x=' '+String(s||'').toLowerCase().replace(/[’‘]/g,"'")+' ';
 const reps=[["can't",'cannot'],["won't",'will not'],["shan't",'shall not'],["isn't",'is not'],["aren't",'are not'],["wasn't",'was not'],["weren't",'were not'],["don't",'do not'],["doesn't",'does not'],["didn't",'did not'],["haven't",'have not'],["hasn't",'has not'],["hadn't",'had not'],["couldn't",'could not'],["wouldn't",'would not'],["shouldn't",'should not'],["mustn't",'must not'],["needn't",'need not'],["i'm",'i am'],["you're",'you are'],["we're",'we are'],["they're",'they are'],["i've",'i have'],["you've",'you have'],["we've",'we have'],["they've",'they have'],["i'll",'i will'],["you'll",'you will'],["we'll",'we will'],["they'll",'they will']];
 reps.forEach(([a,b])=>x=x.split(' '+a+' ').join(' '+b+' '));return x.trim()}
function normBase(s){return contractions(s).replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function variants(s){let base=String(s||'').toLowerCase().replace(/[’‘]/g,"'");let set=new Set([base]);
 const amb=[[/(\b(?:he|she|it|that|there|what|who))'s\b/g,'$1 is'],[/(\b(?:he|she|it|that|there|what|who))'s\b/g,'$1 has'],[/(\b(?:i|you|he|she|we|they))'d\b/g,'$1 would'],[/(\b(?:i|you|he|she|we|they))'d\b/g,'$1 had']];
 let arr=[base];amb.forEach(([r,rep])=>{arr=arr.concat(arr.map(v=>v.replace(r,rep)))});arr.forEach(v=>set.add(normBase(v)));return set}
function isCorrect(user,slot){const uv=variants(user);return (slot.accepted||[]).some(a=>{const av=variants(a);for(const v of uv)if(av.has(v))return true;return false})}
function statusFor(user,slot){if(!slot.gradeable)return 'reference';return isCorrect(user,slot)?'correct':'incorrect'}
function labelText(s,q){const l=String(s.label||q.label||'').replace(/[()]/g,'').trim();return l?'Mục '+l:'Đáp án'}
function inputHtml(uid,ex,q,qi,s,si){const k=ansKey(uid,ex.id,qi,si),val=UI.answers[k]||'';const accepted=s.accepted||[];const isLetter=s.gradeable&&accepted.length&&accepted.every(a=>/^[a-j]$/i.test(String(a).trim()));const long=!isLetter&&(ex.taskType==='open-writing'||String(s.answer||'').length>85);let field='';
 if(isLetter){field='<select class="v24-select" data-v24-answer="'+esc(k)+'"><option value="">-- Chọn --</option>'+Array.from({length:10},(_,i)=>String.fromCharCode(65+i)).map(c=>'<option value="'+c.toLowerCase()+'" '+(String(val).toLowerCase()===c.toLowerCase()?'selected':'')+'>'+c+'</option>').join('')+'</select>'}
 else if(long){field='<textarea class="v24-input" data-v24-answer="'+esc(k)+'" placeholder="Viết câu trả lời của em...">'+esc(val)+'</textarea>'}
 else{field='<input class="v24-input" data-v24-answer="'+esc(k)+'" value="'+esc(val)+'" placeholder="Nhập phần còn thiếu...">'}
 const ok=(accepted||[]).some(a=>/^ok$/i.test(String(a).trim()))?'<button class="v24-ok" data-v24-ok="'+esc(k)+'">Câu đúng - OK</button>':'';
 return '<div class="v24-slot"><label>'+esc(labelText(s,q))+'</label><div class="v24-input-wrap">'+field+ok+'</div></div>'}
function resultHtml(uid,ex,q,qi,s,si){const k=ansKey(uid,ex.id,qi,si),user=UI.answers[k]||'',st=statusFor(user,s);const page=ex.keyPage?('Answer Key trang '+ex.keyPage):'Answer Key trong sách';const trap=(typeof V12_GUIDES!=='undefined'&&V12_GUIDES[uid]&&V12_GUIDES[uid].traps&&V12_GUIDES[uid].traps[0])||'Kiểm tra lại thì, trợ động từ, dạng động từ và trật tự từ.';
 if(st==='correct')return '<div class="v24-result correct"><strong>✓ Chính xác</strong>Câu trả lời của em khớp với Answer Key.<div class="v24-key">'+esc(s.answer)+'</div><span class="v24-meta">Nguồn: '+esc(page)+'</span></div>';
 if(st==='reference')return '<div class="v24-result reference"><strong>Đối chiếu với đáp án mẫu</strong>Đây là câu viết mở hoặc đáp án phức hợp. App không đánh dấu sai máy móc; em hãy so sánh cấu trúc và ý nghĩa với Answer Key.<div class="v24-key">'+esc(s.answer||'Xem đáp án mẫu trong sách.')+'</div><span class="v24-meta">Nguồn: '+esc(page)+'</span></div>';
 return '<div class="v24-result incorrect"><strong>✗ Chưa đúng</strong><div>Đáp án của em: <b>'+esc(user||'(chưa nhập)')+'</b></div><div class="v24-key">Đáp án trong sách: '+esc(s.answer)+'</div><span class="v24-meta">Nguồn: '+esc(page)+'</span><div class="v24-trap"><b>Exam Trap:</b> '+esc(trap)+'</div></div>'}
function questionHtml(uid,ex,q,qi,submitted){const statuses=submitted?(q.slots||[]).map((s,si)=>statusFor(UI.answers[ansKey(uid,ex.id,qi,si)]||'',s)):[];const cls=submitted?(statuses.includes('incorrect')?' incorrect':statuses.every(x=>x==='correct')?' correct':' reference'):'';let h='<article class="v24-question'+cls+'"><div class="v24-qhead"><span class="v24-qnum">'+esc(q.label||qi+1)+'</span><b>Câu '+esc(q.label||qi+1)+'</b></div>';
 if(q.helperText)h+='<div class="v24-helper">'+esc(q.helperText)+'</div>';else h+='<div class="v24-refer"><b>Nội dung câu '+esc(q.label||qi+1)+'</b> nằm trong đề bài chính xác ở cột bên trái. Đọc đúng dòng mang số này, sau đó nhập phần còn thiếu vào ô bên dưới.<br><button type="button" class="v25-question-link" data-v25-source="1">Xem đề bài</button></div>';
 h+='<div class="v24-slots">'+(q.slots||[]).map((s,si)=>inputHtml(uid,ex,q,qi,s,si)+(submitted?resultHtml(uid,ex,q,qi,s,si):'')).join('')+'</div></article>';return h}
function score(ex){let c=0,w=0,r=0;flattenSlots(ex).forEach(x=>{const st=statusFor(UI.answers[x.key]||'',x.s);if(st==='correct')c++;else if(st==='incorrect')w++;else r++});const d=c+w;return {c,w,r,p:d?Math.round(c*100/d):0}}
function panelHtml(uid,u,ex){
 const id=exKey(uid,ex.id),submitted=!!UI.submitted[id],total=flattenSlots(ex).length,done=answered(ex),pct=total?Math.round(done*100/total):0;
 const imgSrc=(window.V25_EXERCISE_IMAGES&&window.V25_EXERCISE_IMAGES[ex.image])||'';
 let h='<div class="v24-panel"><section class="v24-task"><span class="v24-kicker">Bài này yêu cầu em làm gì?</span><h4>'+esc(ex.instructionVi)+'</h4><ul class="v24-steps">'+(ex.steps||[]).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>'+(ex.instructionEn?'<details class="v24-original"><summary>Xem yêu cầu gốc bằng tiếng Anh</summary><div>'+esc(ex.instructionEn)+'</div></details>':'')+'</section>';
 h+='<div class="v25-workspace"><div class="v25-source-column"><section class="v24-source-card" id="v25-source-card"><div class="v24-source-top"><b>Đề bài đầy đủ - đúng Exercise trong sách</b><span>'+esc(u.book)+' · Unit '+esc(u.unit)+' · Exercise '+esc(ex.id)+'</span></div><img class="v24-source-img" data-v26-image-key="'+esc(ex.image)+'" data-v24-zoom="'+esc(imgSrc)+'" '+(imgSrc?'src="'+esc(imgSrc)+'"':'')+' loading="eager" alt="Exercise '+esc(ex.id)+'" onerror="this.style.display=\'none\';this.nextElementSibling.classList.add(\'show\')"><div class="v25-image-fallback">Không tải được khung đề. Hãy kiểm tra rằng tất cả các tệp <b>exercise-images-*.js</b> đã được đặt cùng thư mục với <b>index.html</b>.</div><div class="v25-source-status">✓ Khung đề đã được đóng gói cùng ứng dụng, không còn phụ thuộc thư mục ảnh rời.</div><button type="button" class="v25-open-source" data-v24-zoom="'+esc(imgSrc)+'">Mở đề toàn màn hình</button><p class="v24-source-note">Đọc câu mang đúng số ở khung đề này. Các ô trả lời tương ứng được xếp theo hàng dọc ở cột bên phải.</p></section></div><div class="v25-answer-column">';
 h+='<div class="v24-progress-row"><div class="v24-progress"><i style="width:'+pct+'%"></i></div><b data-v24-progress>'+done+'/'+total+' mục đã trả lời</b></div>';
 if(submitted){const s=score(ex);h+='<div class="v24-score"><div><b>'+s.p+'%</b><span>điểm tự chấm</span></div><div><b>'+s.c+'</b><span>đúng</span></div><div><b>'+s.w+'</b><span>chưa đúng</span></div><div><b>'+s.r+'</b><span>đáp án mẫu</span></div></div>'}
 h+='<div class="v24-list">'+(ex.questions||[]).map((q,qi)=>questionHtml(uid,ex,q,qi,submitted)).join('')+'</div>';
 h+='<div class="v24-actions"><button class="v24-btn primary" data-v24-submit="1" '+(!allAnswered(ex)?'disabled':'')+'>Nộp bài và chấm theo Answer Key</button>'+(submitted?'<button class="v24-btn" data-v24-retry="1">Làm lại câu sai</button>':'')+'<button class="v24-btn danger" data-v24-reset="1">Xóa toàn bộ bài làm</button></div><p class="v24-legend">Đáp án chỉ hiện sau khi nộp. Câu viết mở hoặc Answer Key có nhiều cách diễn đạt được hiển thị để đối chiếu và không bị tính sai máy móc.</p></div></div></div>';return h}
function sectionHtml(){const uid=currentUnit(),u=V24_COMPLETE_DATA[uid];if(!u)return '<section class="v11-exercises v24-exercises"><div class="v24-empty">Không tìm thấy dữ liệu Exercise của Unit này.</div></section>';let ai=Number(UI.active[uid]||0);if(ai<0||ai>=u.exercises.length)ai=0;UI.active[uid]=ai;const tabs=u.exercises.map((ex,i)=>'<button class="v24-tab '+(i===ai?'active ':'')+(UI.submitted[exKey(uid,ex.id)]?'done':'')+'" data-v24-tab="'+i+'">Exercise '+esc(ex.id)+'</button>').join('');return '<section class="v11-exercises v24-exercises" data-v24-unit="'+esc(uid)+'"><div class="v24-head"><h3>Bài tập Grammar in Use - đầy đủ đề bài</h3><p>Mỗi Exercise dùng đúng khung đề từ sách, các ô trả lời xếp theo hàng dọc và chấm bằng Answer Key của chính sách.</p><div class="v24-coverage"><span>✓ '+V24_COMPLETE_STATS.units+'/360 Unit</span><span>✓ '+V24_COMPLETE_STATS.exercises+' Exercise</span><span>✓ '+V24_COMPLETE_STATS.slots+' mục trả lời</span><span>✓ Không dùng AI để chấm</span></div></div><div class="v24-tabs">'+tabs+'</div>'+panelHtml(uid,u,u.exercises[ai])+'</section>'}
function mount(){const detail=document.querySelector('#unit-detail');if(!detail||!currentUnit())return;const old=detail.querySelector('.v11-exercises,.v19-exercises,.v10-exercises');if(old)old.outerHTML=sectionHtml();else detail.insertAdjacentHTML('beforeend',sectionHtml());document.title='Albert Grammar Việt Nam V26 - GitHub Web';if(window.V26_applyExerciseImages)window.V26_applyExerciseImages(detail)}
function refresh(){const old=document.querySelector('.v24-exercises');if(old){old.outerHTML=sectionHtml();if(window.V26_applyExerciseImages)window.V26_applyExerciseImages(document.querySelector('#unit-detail'))}else mount()}
const previous=window.renderUnitDetail;window.renderUnitDetail=function(){if(typeof previous==='function')previous.apply(this,arguments);setTimeout(mount,0)};
window.addEventListener('load',()=>setTimeout(()=>{if(typeof state!=='undefined'&&state&&state.tab==='grammar')mount();const q=document.body;if(!document.querySelector('.v24-zoom'))q.insertAdjacentHTML('beforeend','<div class="v24-zoom"><button aria-label="Đóng">×</button><img alt="Phóng to đề bài"></div>')},180));
document.addEventListener('click',e=>{const sourceBtn=e.target.closest('[data-v25-source]');if(sourceBtn){const card=document.querySelector('#v25-source-card');if(card){card.scrollIntoView({behavior:'smooth',block:'start'});card.animate([{boxShadow:'0 0 0 0 rgba(57,119,238,0)'},{boxShadow:'0 0 0 6px rgba(57,119,238,.25)'},{boxShadow:'0 0 0 0 rgba(57,119,238,0)'}],{duration:900});}return}const tab=e.target.closest('[data-v24-tab]');if(tab){UI.active[currentUnit()]=Number(tab.dataset.v24Tab);save();refresh();return}const ok=e.target.closest('[data-v24-ok]');if(ok){UI.answers[ok.dataset.v24Ok]='OK';save();refresh();return}const submit=e.target.closest('[data-v24-submit]');if(submit){const u=unitData(),ex=u&&u.exercises[Number(UI.active[currentUnit()]||0)];if(ex&&allAnswered(ex)){UI.submitted[exKey(currentUnit(),ex.id)]=true;save();refresh()}return}const reset=e.target.closest('[data-v24-reset]');if(reset){const u=unitData(),ex=u&&u.exercises[Number(UI.active[currentUnit()]||0)];if(ex&&confirm('Xóa toàn bộ câu trả lời của Exercise này?')){flattenSlots(ex).forEach(x=>delete UI.answers[x.key]);delete UI.submitted[exKey(currentUnit(),ex.id)];save();refresh()}return}const retry=e.target.closest('[data-v24-retry]');if(retry){const u=unitData(),ex=u&&u.exercises[Number(UI.active[currentUnit()]||0)];if(ex){flattenSlots(ex).forEach(x=>{if(statusFor(UI.answers[x.key]||'',x.s)!=='correct')delete UI.answers[x.key]});delete UI.submitted[exKey(currentUnit(),ex.id)];save();refresh()}return}const zoom=e.target.closest('[data-v24-zoom]');if(zoom){const z=document.querySelector('.v24-zoom');z.querySelector('img').src=zoom.dataset.v24Zoom;z.classList.add('open');return}if(e.target.closest('.v24-zoom button')||e.target.classList.contains('v24-zoom'))document.querySelector('.v24-zoom')?.classList.remove('open')});
document.addEventListener('input',e=>{const f=e.target.closest('[data-v24-answer]');if(!f)return;UI.answers[f.dataset.v24Answer]=f.value;save();const u=unitData(),ex=u&&u.exercises[Number(UI.active[currentUnit()]||0)];if(!ex)return;const sec=f.closest('.v24-exercises'),p=sec&&sec.querySelector('[data-v24-progress]'),bar=sec&&sec.querySelector('.v24-progress i'),btn=sec&&sec.querySelector('[data-v24-submit]');const t=flattenSlots(ex).length,d=answered(ex);if(p)p.textContent=d+'/'+t+' mục đã trả lời';if(bar)bar.style.width=(t?Math.round(d*100/t):0)+'%';if(btn)btn.disabled=!allAnswered(ex)});
})();
